# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/english

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/french
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Projets
        url: '#projects'
        weight: 20
      - name: Expérience
        url: '#experience'
        weight: 30
      - name: Contact
        url: '#contact'
        weight: 40
